spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/scaims
    username: mridula
    password: Mridula@123
    driver-class-name: org.postgresql.Driver

  mail:
    username: abhinav.singh@jellyfishtechnologies.com
    password: evjkcwytstpyzezo

