spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scaims5
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  mail:
    username: mridula.swami@jellyfishtechnologies.com
    password: khjjmmakiebvlstu

