server:
  forward-headers-strategy: framework

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scaims_prod
    username: abhisingh
    password: Singh@123
    driver-class-name: org.postgresql.Driver

  mail:
    username: abhinav.singh@jellyfishtechnologies.com
    password: <your-existing-mail-password>

springdoc:
  swagger-ui:
    config-url: /api/prod/user-management-service/v3/api-docs/swagger-config
    url: /api/prod/user-management-service/v3/api-docs
