spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scaims
    username: postgres

    password: Singh@123
    driver-class-name: org.postgresql.Driver

  mail:
    username: abhinav.singh@jellyfishtechnologies.com
    password: evjkcwytstpyzezo

