package com.schoolerp.usermanagement.modules.notification.enums;

public enum NotificationType {
    COMPLAINT_SUBMITTED,
    COMPLAINT_ACKNOWLEDGED,
    COMPLAINT_STATUS_UPDATED,
    COMPLAINT_RESOLVED,
    COMPLAINT_REJECTED,
    WORK_ORDER_ASSIGNED,
    WORK_ORDER_STATUS_CHANGED,
    WORK_ORDER_COMPLETED,
    USER_REGISTERED,
    PASSWORD_CHANGED,
    ASSET_IMPORTED,
    ASSET_CREATED,
    SYSTEM_ALERT
}
